services:
  - type: web
    name: pps-backend
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn config.wsgi:application"
    healthCheckPath: /admin/login/
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: CORS_ALLOWED_ORIGIN_REGEXES
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: PYTHON_VERSION
        value: "3.13.0"
