# Generated by Django 5.2.16 on 2026-07-08 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('scenario', models.TextField(help_text='Caso de falla: la situación problemática inicial (C).')),
                ('guiding_questions', models.TextField(help_text='Preguntas de análisis guiado (A).')),
                ('theory', models.TextField(help_text='Formalización conceptual (F).')),
                ('visual_model', models.CharField(choices=[('process_states', 'Diagrama de estados de procesos'), ('cpu_timeline', 'Línea de tiempo de planificación'), ('resource_graph', 'Grafo de asignación de recursos'), ('memory_map', 'Mapa de memoria virtual'), ('fs_sequence', 'Secuencia de escritura en filesystem')], max_length=30)),
                ('visual_model_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['topic', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legajo', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('question_type', models.CharField(choices=[('single_choice', 'Opción única'), ('multiple_choice', 'Opción múltiple'), ('fill_blank', 'Completar')], max_length=20)),
                ('justification', models.TextField(help_text='Explicación mostrada tras responder.')),
                ('conceptual_error', models.CharField(blank=True, help_text='Error conceptual que la pregunta busca detectar.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='cafe.case')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='cafe.topic')),
            ],
            options={
                'ordering': ['topic', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='cafe.question')),
            ],
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('status', models.CharField(choices=[('waiting', 'Esperando'), ('active', 'Activa'), ('finished', 'Finalizada')], default='waiting', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quiz_sessions', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='cafe.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='cafe.quizsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participations', to='cafe.student')),
            ],
            options={
                'unique_together': {('session', 'student')},
            },
        ),
        migrations.CreateModel(
            name='SessionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('points', models.PositiveIntegerField(default=100)),
                ('duration_seconds', models.PositiveSmallIntegerField(default=20)),
                ('grace_seconds', models.PositiveSmallIntegerField(default=2)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('revealed_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cafe.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_questions', to='cafe.quizsession')),
            ],
            options={
                'ordering': ['session', 'order'],
                'unique_together': {('session', 'order')},
            },
        ),
        migrations.AddField(
            model_name='case',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='cafe.topic'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_text', models.CharField(blank=True, max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('score', models.PositiveIntegerField(default=0)),
                ('response_seconds', models.FloatField(default=0.0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='cafe.participant')),
                ('selected_options', models.ManyToManyField(blank=True, to='cafe.questionoption')),
                ('session_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='cafe.sessionquestion')),
            ],
            options={
                'unique_together': {('participant', 'session_question')},
            },
        ),
    ]
