# Generated by Django 5.2.16 on 2026-07-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='avatar',
            field=models.PositiveSmallIntegerField(default=0, help_text='Índice del glifo elegido (0-7) en el frontend.'),
        ),
        migrations.AddField(
            model_name='student',
            name='theme',
            field=models.CharField(choices=[('dark', 'Oscuro'), ('light', 'Claro')], default='dark', max_length=5),
        ),
    ]
