# Generated by Django 5.2.16 on 2026-07-10 20:52, reordered by hand so the
# data backfill runs between adding the new columns and dropping the old
# ones — see backfill_quizzes below.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_quizzes(apps, schema_editor):
    """Las QuizSession/Question que ya existían antes de este cambio no
    tenían un Quiz dueño — se les crea uno de respaldo por sesión, copiando
    el order/points/duration/grace que hoy vive en SessionQuestion (todavía
    presente en este punto de la migración) a la Question correspondiente."""
    QuizSession = apps.get_model('cafe', 'QuizSession')
    Quiz = apps.get_model('cafe', 'Quiz')

    for session in QuizSession.objects.filter(quiz__isnull=True):
        quiz = Quiz.objects.create(
            topic_id=session.topic_id,
            host_id=session.host_id,
            title=f'Cuestionario {session.code}',
            is_shared=False,
        )
        for sq in session.session_questions.select_related('question').order_by('order'):
            q = sq.question
            q.quiz_id = quiz.id
            q.order = sq.order
            q.points = sq.points
            q.duration_seconds = sq.duration_seconds
            q.grace_seconds = sq.grace_seconds
            q.save(update_fields=['quiz', 'order', 'points', 'duration_seconds', 'grace_seconds'])
        session.quiz_id = quiz.id
        session.save(update_fields=['quiz'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_teacherprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. Modelo nuevo + columnas nuevas (todas nullable/con default: no
        # tocan filas existentes).
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('is_shared', models.BooleanField(default=False, help_text='Si está tildado, cualquier docente puede verlo, reusarlo y eliminarlo.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quizzes', to='cafe.topic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='duration_seconds',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='question',
            name='grace_seconds',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, help_text='Orden dentro de su Quiz.'),
        ),
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cafe.quiz'),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='cafe.quiz'),
        ),
        # 2. Backfill: crea un Quiz por cada QuizSession preexistente y le
        # copia el order/points/duration/grace a sus Question.
        migrations.RunPython(backfill_quizzes, noop_reverse),
        # 3. Sacar el unique_together/ordering viejos ANTES de borrar la
        # columna `order` — en SQLite el drop de columna reconstruye la
        # tabla y falla si todavía hay un índice único apuntando a ella.
        migrations.AlterModelOptions(
            name='sessionquestion',
            options={'ordering': ['session', 'question__order']},
        ),
        migrations.AlterUniqueTogether(
            name='sessionquestion',
            unique_together={('session', 'question')},
        ),
        migrations.AlterField(
            model_name='sessionquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.question'),
        ),
        # 4. Recién ahora se pueden borrar las columnas viejas de
        # SessionQuestion sin perder datos.
        migrations.RemoveField(
            model_name='sessionquestion',
            name='duration_seconds',
        ),
        migrations.RemoveField(
            model_name='sessionquestion',
            name='grace_seconds',
        ),
        migrations.RemoveField(
            model_name='sessionquestion',
            name='order',
        ),
        migrations.RemoveField(
            model_name='sessionquestion',
            name='points',
        ),
    ]
