# Generated by Django 5.2.16 on 2026-07-10 21:40, reordered by hand to
# backfill Participant.total_score from the existing Answer rows before
# dropping Quiz.is_shared (unrelated, but kept in the same migration).

from django.conf import settings
from django.db import migrations, models
from django.db.models import Sum


def backfill_total_score(apps, schema_editor):
    Participant = apps.get_model('cafe', 'Participant')
    for participant in Participant.objects.annotate(sum_score=Sum('answers__score')):
        participant.total_score = participant.sum_score or 0
        participant.save(update_fields=['total_score'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_persist_quizzes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='total_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(backfill_total_score, noop_reverse),
        migrations.RemoveField(
            model_name='quiz',
            name='is_shared',
        ),
        migrations.AddField(
            model_name='quiz',
            name='shared_with',
            field=models.ManyToManyField(blank=True, help_text='Docentes puntuales que además del dueño pueden verlo y arrancar sesiones — solo el dueño puede editarlo o eliminarlo.', related_name='shared_quizzes', to=settings.AUTH_USER_MODEL),
        ),
    ]
