# Generated by Django 5.2.16 on 2026-07-13 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0006_alter_question_options_remove_quiz_topic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='visual_model',
            field=models.CharField(choices=[('process_states', 'Diagrama de estados de procesos'), ('cpu_timeline', 'Línea de tiempo de planificación'), ('resource_graph', 'Grafo de asignación de recursos'), ('memory_map', 'Mapa de memoria virtual'), ('fs_sequence', 'Secuencia de escritura en filesystem'), ('priority_queue_timeline', 'Cola de prioridad con línea de tiempo')], max_length=30),
        ),
    ]
