# Generated by Django 5.2.16 on 2026-07-13 23:35

import django.db.models.deletion
from django.db import migrations, models


def backfill_case_graphics(apps, schema_editor):
    Case = apps.get_model('cafe', 'Case')
    CaseGraphic = apps.get_model('cafe', 'CaseGraphic')
    for case in Case.objects.all():
        CaseGraphic.objects.create(case=case, topic_id=case.topic_id, data=case.visual_model_data)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0007_alter_case_visual_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseGraphic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='graphic', to='cafe.case')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='graphics', to='cafe.topic')),
            ],
        ),
        migrations.RunPython(backfill_case_graphics, noop),
        migrations.RemoveField(
            model_name='case',
            name='visual_model',
        ),
        migrations.RemoveField(
            model_name='case',
            name='visual_model_data',
        ),
    ]
