# Generated by Django 5.2.16 on 2026-07-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0009_case_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.TextField(blank=True, default='', help_text='Data URI opcional para el enunciado (mismo criterio que QuestionOption.image).'),
        ),
    ]
