# Generated by Django 5.2.16 on 2026-07-21 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0010_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='shared_with_comisiones',
            field=models.JSONField(blank=True, default=list, help_text='Comisiones (Student.comision) con las que se compartió este cuestionario para repaso — no confundir con `shared_with`, que es entre docentes. Solo el dueño puede modificarlo.'),
        ),
        migrations.AddField(
            model_name='student',
            name='comision',
            field=models.CharField(blank=True, default='', help_text='Comisión del alumno — se usa para compartirle cuestionarios de repaso.', max_length=20),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.PositiveIntegerField(default=0)),
                ('answers', models.JSONField(default=list, help_text='Snapshot por pregunta: enunciado, opciones (con is_correct) y qué marcó el alumno.')),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='cafe.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='cafe.student')),
            ],
            options={
                'ordering': ['-played_at'],
                'unique_together': {('student', 'quiz')},
            },
        ),
    ]
